namespace CoronaVirusStatistics
{
    partial class GraphsForm
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            this.graphImage = new System.Windows.Forms.PictureBox();
            this.graphBttn = new System.Windows.Forms.Button();
            this.comboBox1 = new System.Windows.Forms.ComboBox();
            this.comboBox2 = new System.Windows.Forms.ComboBox();
            this.comboBox3 = new System.Windows.Forms.ComboBox();
            this.comboBox4 = new System.Windows.Forms.ComboBox();
            this.label1 = new System.Windows.Forms.Label();
            this.label2 = new System.Windows.Forms.Label();
            this.label3 = new System.Windows.Forms.Label();
            this.label4 = new System.Windows.Forms.Label();
            ((System.ComponentModel.ISupportInitialize)(this.graphImage)).BeginInit();
            this.SuspendLayout();
            // 
            // graphImage
            // 
            this.graphImage.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
            this.graphImage.Location = new System.Drawing.Point(344, 24);
            this.graphImage.Name = "graphImage";
            this.graphImage.Size = new System.Drawing.Size(420, 400);
            this.graphImage.TabIndex = 0;
            this.graphImage.TabStop = false;
            // 
            // graphBttn
            // 
            this.graphBttn.Location = new System.Drawing.Point(54, 410);
            this.graphBttn.Name = "graphBttn";
            this.graphBttn.Size = new System.Drawing.Size(142, 28);
            this.graphBttn.TabIndex = 1;
            this.graphBttn.Text = "Make Graph";
            this.graphBttn.UseVisualStyleBackColor = true;
            this.graphBttn.Click += new System.EventHandler(this.graphBttn_Click);
            // 
            // comboBox1
            // 
            this.comboBox1.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList;
            this.comboBox1.Font = new System.Drawing.Font("Microsoft Sans Serif", 9F);
            this.comboBox1.FormattingEnabled = true;
            this.comboBox1.Items.AddRange(new object[] {
            "World",
            "North America",
            "Europe",
            "Asia",
            "South America",
            "Oceania",
            "Africa",
            "USA",
            "Spain",
            "Italy",
            "France",
            "Germany",
            "China",
            "UK",
            "Iran",
            "Turkey",
            "Belgium",
            "Switzerland",
            "Netherlands",
            "Canada",
            "Brazil",
            "Portugal",
            "Austria",
            "Russia",
            "Israel",
            "S. Korea",
            "Sweden",
            "Ireland",
            "India",
            "Ecuador",
            "Chile",
            "Peru",
            "Norway",
            "Poland",
            "Australia",
            "Japan",
            "Denmark",
            "Romania",
            "Czechia",
            "Pakistan",
            "Malaysia",
            "Philippines",
            "Saudi Arabia",
            "Mexico",
            "Indonesia",
            "UAE",
            "Serbia",
            "Luxembourg",
            "Panama",
            "Finland",
            "Dominican Republic",
            "Qatar",
            "Thailand",
            "Ukraine",
            "Colombia",
            "Singapoure",
            "Belarus",
            "Greece",
            "South Africa",
            "Argentina",
            "Egypt",
            "Algeria",
            "Iceland",
            "Moldova",
            "Morocco",
            "Croatia",
            "Iraq",
            "New Zealand",
            "Hungary",
            "Estonia",
            "Slovenia",
            "Kuwait",
            "Azerbaijan",
            "Bahrain",
            "Lithuania",
            "Hong Kong",
            "Armenia",
            "Bosnia and Herzegovina",
            "Kazakhstan",
            "Cameroon",
            "Uzbekistan",
            "North Macedonia",
            "Diamond Princess",
            "Tunisia",
            "Bulgaria",
            "Latvia",
            "Cuba",
            "Lebanon",
            "Cyprus",
            "Andorra",
            "Costa Rica",
            "Afghanistan",
            "Oman",
            "Uruguay",
            "Bangladesh",
            "Ivory Coast",
            "Burkina faso",
            "Albania",
            "Ghana",
            "Channel Islands",
            "Honduras",
            "Réunion",
            "Taiwan",
            "Jordan",
            "Malta",
            "San Marino",
            "Kyrgyzstan",
            "Mauritius",
            "Nigeria",
            "Senegal",
            "Bolivia",
            "Palestine",
            "Montenegro",
            "Vietnam",
            "Guinea",
            "Georgia",
            "Isle of Man",
            "DRC",
            "Sri Lanka",
            "Mayotte",
            "Kenya",
            "Djibouti",
            "Faeroe Islands",
            "Venezuela",
            "Martinique",
            "Guandeloupe",
            "Guatemala",
            "Brunei",
            "Paraguay",
            "Gibraltar",
            "Cambodia",
            "El Salvador",
            "Rwanda",
            "Trinidad and Tobago",
            "Madagascar",
            "Monaco",
            "Aruba",
            "Mali",
            "French Guiana",
            "Liechtenstein",
            "Togo",
            "Ethiopia",
            "Barbados",
            "Jamaica",
            "Congo",
            "Uganda",
            "French Polinesia",
            "Sint Maarten",
            "Liberia",
            "Bermuda",
            "Gabon",
            "Cayman Islands",
            "Macao",
            "Bahamas",
            "Guyana",
            "Zambia",
            "Guinea-Bissau",
            "Benin",
            "Eritrea",
            "Tanzania",
            "Saint Martin",
            "Myanmar",
            "Haiti",
            "Syria",
            "Libya",
            "Antigua and Barbuda",
            "Somalia",
            "Mozambique",
            "Angola",
            "Sudan",
            "Maldives",
            "Equatorial Guinea",
            "Laos",
            "New Calcedonia",
            "Dominica",
            "Fiji",
            "Mongolia",
            "Namibia",
            "Saint Lucia",
            "Curaçao",
            "Grenada",
            "Zimbabwe",
            "Belize",
            "Botswana",
            "Malwi",
            "Saint Kitts and Nevis",
            "St. Vincent Grenadies",
            "Eswatini",
            "Chad",
            "Greenland",
            "Seychelles",
            "Suriname",
            "MS Zaandam",
            "Gambia",
            "Nepal",
            "Montserrat",
            "Cabo Verde",
            "Turks and Caicos",
            "Vatican City",
            "Sierra Leone",
            "Mauritania",
            "St. Barth",
            "Bhutan",
            "Burundi",
            "Falkland Islands",
            "Sao Tome and Principe",
            "South Sudan",
            "Anguilla",
            "British Virgin Islands",
            "Caribbean Netherlands",
            "Papua New Guinea",
            "Timor-Leste",
            "Saint  Pierre Miquelon",
            "Yemen"});
            this.comboBox1.Location = new System.Drawing.Point(55, 60);
            this.comboBox1.Margin = new System.Windows.Forms.Padding(3, 2, 3, 2);
            this.comboBox1.Name = "comboBox1";
            this.comboBox1.Size = new System.Drawing.Size(220, 26);
            this.comboBox1.TabIndex = 6;
            // 
            // comboBox2
            // 
            this.comboBox2.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList;
            this.comboBox2.Font = new System.Drawing.Font("Microsoft Sans Serif", 9F);
            this.comboBox2.FormattingEnabled = true;
            this.comboBox2.Items.AddRange(new object[] {
            "World",
            "North America",
            "Europe",
            "Asia",
            "South America",
            "Oceania",
            "Africa",
            "USA",
            "Spain",
            "Italy",
            "France",
            "Germany",
            "China",
            "UK",
            "Iran",
            "Turkey",
            "Belgium",
            "Switzerland",
            "Netherlands",
            "Canada",
            "Brazil",
            "Portugal",
            "Austria",
            "Russia",
            "Israel",
            "S. Korea",
            "Sweden",
            "Ireland",
            "India",
            "Ecuador",
            "Chile",
            "Peru",
            "Norway",
            "Poland",
            "Australia",
            "Japan",
            "Denmark",
            "Romania",
            "Czechia",
            "Pakistan",
            "Malaysia",
            "Philippines",
            "Saudi Arabia",
            "Mexico",
            "Indonesia",
            "UAE",
            "Serbia",
            "Luxembourg",
            "Panama",
            "Finland",
            "Dominican Republic",
            "Qatar",
            "Thailand",
            "Ukraine",
            "Colombia",
            "Singapoure",
            "Belarus",
            "Greece",
            "South Africa",
            "Argentina",
            "Egypt",
            "Algeria",
            "Iceland",
            "Moldova",
            "Morocco",
            "Croatia",
            "Iraq",
            "New Zealand",
            "Hungary",
            "Estonia",
            "Slovenia",
            "Kuwait",
            "Azerbaijan",
            "Bahrain",
            "Lithuania",
            "Hong Kong",
            "Armenia",
            "Bosnia and Herzegovina",
            "Kazakhstan",
            "Cameroon",
            "Uzbekistan",
            "North Macedonia",
            "Diamond Princess",
            "Tunisia",
            "Bulgaria",
            "Latvia",
            "Cuba",
            "Lebanon",
            "Cyprus",
            "Andorra",
            "Costa Rica",
            "Afghanistan",
            "Oman",
            "Uruguay",
            "Bangladesh",
            "Ivory Coast",
            "Burkina faso",
            "Albania",
            "Ghana",
            "Channel Islands",
            "Honduras",
            "Réunion",
            "Taiwan",
            "Jordan",
            "Malta",
            "San Marino",
            "Kyrgyzstan",
            "Mauritius",
            "Nigeria",
            "Senegal",
            "Bolivia",
            "Palestine",
            "Montenegro",
            "Vietnam",
            "Guinea",
            "Georgia",
            "Isle of Man",
            "DRC",
            "Sri Lanka",
            "Mayotte",
            "Kenya",
            "Djibouti",
            "Faeroe Islands",
            "Venezuela",
            "Martinique",
            "Guandeloupe",
            "Guatemala",
            "Brunei",
            "Paraguay",
            "Gibraltar",
            "Cambodia",
            "El Salvador",
            "Rwanda",
            "Trinidad and Tobago",
            "Madagascar",
            "Monaco",
            "Aruba",
            "Mali",
            "French Guiana",
            "Liechtenstein",
            "Togo",
            "Ethiopia",
            "Barbados",
            "Jamaica",
            "Congo",
            "Uganda",
            "French Polinesia",
            "Sint Maarten",
            "Liberia",
            "Bermuda",
            "Gabon",
            "Cayman Islands",
            "Macao",
            "Bahamas",
            "Guyana",
            "Zambia",
            "Guinea-Bissau",
            "Benin",
            "Eritrea",
            "Tanzania",
            "Saint Martin",
            "Myanmar",
            "Haiti",
            "Syria",
            "Libya",
            "Antigua and Barbuda",
            "Somalia",
            "Mozambique",
            "Angola",
            "Sudan",
            "Maldives",
            "Equatorial Guinea",
            "Laos",
            "New Calcedonia",
            "Dominica",
            "Fiji",
            "Mongolia",
            "Namibia",
            "Saint Lucia",
            "Curaçao",
            "Grenada",
            "Zimbabwe",
            "Belize",
            "Botswana",
            "Malwi",
            "Saint Kitts and Nevis",
            "St. Vincent Grenadies",
            "Eswatini",
            "Chad",
            "Greenland",
            "Seychelles",
            "Suriname",
            "MS Zaandam",
            "Gambia",
            "Nepal",
            "Montserrat",
            "Cabo Verde",
            "Turks and Caicos",
            "Vatican City",
            "Sierra Leone",
            "Mauritania",
            "St. Barth",
            "Bhutan",
            "Burundi",
            "Falkland Islands",
            "Sao Tome and Principe",
            "South Sudan",
            "Anguilla",
            "British Virgin Islands",
            "Caribbean Netherlands",
            "Papua New Guinea",
            "Timor-Leste",
            "Saint  Pierre Miquelon",
            "Yemen"});
            this.comboBox2.Location = new System.Drawing.Point(55, 156);
            this.comboBox2.Margin = new System.Windows.Forms.Padding(3, 2, 3, 2);
            this.comboBox2.Name = "comboBox2";
            this.comboBox2.Size = new System.Drawing.Size(220, 26);
            this.comboBox2.TabIndex = 7;
            // 
            // comboBox3
            // 
            this.comboBox3.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList;
            this.comboBox3.Font = new System.Drawing.Font("Microsoft Sans Serif", 9F);
            this.comboBox3.FormattingEnabled = true;
            this.comboBox3.Items.AddRange(new object[] {
            "World",
            "North America",
            "Europe",
            "Asia",
            "South America",
            "Oceania",
            "Africa",
            "USA",
            "Spain",
            "Italy",
            "France",
            "Germany",
            "China",
            "UK",
            "Iran",
            "Turkey",
            "Belgium",
            "Switzerland",
            "Netherlands",
            "Canada",
            "Brazil",
            "Portugal",
            "Austria",
            "Russia",
            "Israel",
            "S. Korea",
            "Sweden",
            "Ireland",
            "India",
            "Ecuador",
            "Chile",
            "Peru",
            "Norway",
            "Poland",
            "Australia",
            "Japan",
            "Denmark",
            "Romania",
            "Czechia",
            "Pakistan",
            "Malaysia",
            "Philippines",
            "Saudi Arabia",
            "Mexico",
            "Indonesia",
            "UAE",
            "Serbia",
            "Luxembourg",
            "Panama",
            "Finland",
            "Dominican Republic",
            "Qatar",
            "Thailand",
            "Ukraine",
            "Colombia",
            "Singapoure",
            "Belarus",
            "Greece",
            "South Africa",
            "Argentina",
            "Egypt",
            "Algeria",
            "Iceland",
            "Moldova",
            "Morocco",
            "Croatia",
            "Iraq",
            "New Zealand",
            "Hungary",
            "Estonia",
            "Slovenia",
            "Kuwait",
            "Azerbaijan",
            "Bahrain",
            "Lithuania",
            "Hong Kong",
            "Armenia",
            "Bosnia and Herzegovina",
            "Kazakhstan",
            "Cameroon",
            "Uzbekistan",
            "North Macedonia",
            "Diamond Princess",
            "Tunisia",
            "Bulgaria",
            "Latvia",
            "Cuba",
            "Lebanon",
            "Cyprus",
            "Andorra",
            "Costa Rica",
            "Afghanistan",
            "Oman",
            "Uruguay",
            "Bangladesh",
            "Ivory Coast",
            "Burkina faso",
            "Albania",
            "Ghana",
            "Channel Islands",
            "Honduras",
            "Réunion",
            "Taiwan",
            "Jordan",
            "Malta",
            "San Marino",
            "Kyrgyzstan",
            "Mauritius",
            "Nigeria",
            "Senegal",
            "Bolivia",
            "Palestine",
            "Montenegro",
            "Vietnam",
            "Guinea",
            "Georgia",
            "Isle of Man",
            "DRC",
            "Sri Lanka",
            "Mayotte",
            "Kenya",
            "Djibouti",
            "Faeroe Islands",
            "Venezuela",
            "Martinique",
            "Guandeloupe",
            "Guatemala",
            "Brunei",
            "Paraguay",
            "Gibraltar",
            "Cambodia",
            "El Salvador",
            "Rwanda",
            "Trinidad and Tobago",
            "Madagascar",
            "Monaco",
            "Aruba",
            "Mali",
            "French Guiana",
            "Liechtenstein",
            "Togo",
            "Ethiopia",
            "Barbados",
            "Jamaica",
            "Congo",
            "Uganda",
            "French Polinesia",
            "Sint Maarten",
            "Liberia",
            "Bermuda",
            "Gabon",
            "Cayman Islands",
            "Macao",
            "Bahamas",
            "Guyana",
            "Zambia",
            "Guinea-Bissau",
            "Benin",
            "Eritrea",
            "Tanzania",
            "Saint Martin",
            "Myanmar",
            "Haiti",
            "Syria",
            "Libya",
            "Antigua and Barbuda",
            "Somalia",
            "Mozambique",
            "Angola",
            "Sudan",
            "Maldives",
            "Equatorial Guinea",
            "Laos",
            "New Calcedonia",
            "Dominica",
            "Fiji",
            "Mongolia",
            "Namibia",
            "Saint Lucia",
            "Curaçao",
            "Grenada",
            "Zimbabwe",
            "Belize",
            "Botswana",
            "Malwi",
            "Saint Kitts and Nevis",
            "St. Vincent Grenadies",
            "Eswatini",
            "Chad",
            "Greenland",
            "Seychelles",
            "Suriname",
            "MS Zaandam",
            "Gambia",
            "Nepal",
            "Montserrat",
            "Cabo Verde",
            "Turks and Caicos",
            "Vatican City",
            "Sierra Leone",
            "Mauritania",
            "St. Barth",
            "Bhutan",
            "Burundi",
            "Falkland Islands",
            "Sao Tome and Principe",
            "South Sudan",
            "Anguilla",
            "British Virgin Islands",
            "Caribbean Netherlands",
            "Papua New Guinea",
            "Timor-Leste",
            "Saint  Pierre Miquelon",
            "Yemen"});
            this.comboBox3.Location = new System.Drawing.Point(55, 256);
            this.comboBox3.Margin = new System.Windows.Forms.Padding(3, 2, 3, 2);
            this.comboBox3.Name = "comboBox3";
            this.comboBox3.Size = new System.Drawing.Size(220, 26);
            this.comboBox3.TabIndex = 8;
            // 
            // comboBox4
            // 
            this.comboBox4.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList;
            this.comboBox4.Font = new System.Drawing.Font("Microsoft Sans Serif", 9F);
            this.comboBox4.FormattingEnabled = true;
            this.comboBox4.Items.AddRange(new object[] {
            "World",
            "North America",
            "Europe",
            "Asia",
            "South America",
            "Oceania",
            "Africa",
            "USA",
            "Spain",
            "Italy",
            "France",
            "Germany",
            "China",
            "UK",
            "Iran",
            "Turkey",
            "Belgium",
            "Switzerland",
            "Netherlands",
            "Canada",
            "Brazil",
            "Portugal",
            "Austria",
            "Russia",
            "Israel",
            "S. Korea",
            "Sweden",
            "Ireland",
            "India",
            "Ecuador",
            "Chile",
            "Peru",
            "Norway",
            "Poland",
            "Australia",
            "Japan",
            "Denmark",
            "Romania",
            "Czechia",
            "Pakistan",
            "Malaysia",
            "Philippines",
            "Saudi Arabia",
            "Mexico",
            "Indonesia",
            "UAE",
            "Serbia",
            "Luxembourg",
            "Panama",
            "Finland",
            "Dominican Republic",
            "Qatar",
            "Thailand",
            "Ukraine",
            "Colombia",
            "Singapoure",
            "Belarus",
            "Greece",
            "South Africa",
            "Argentina",
            "Egypt",
            "Algeria",
            "Iceland",
            "Moldova",
            "Morocco",
            "Croatia",
            "Iraq",
            "New Zealand",
            "Hungary",
            "Estonia",
            "Slovenia",
            "Kuwait",
            "Azerbaijan",
            "Bahrain",
            "Lithuania",
            "Hong Kong",
            "Armenia",
            "Bosnia and Herzegovina",
            "Kazakhstan",
            "Cameroon",
            "Uzbekistan",
            "North Macedonia",
            "Diamond Princess",
            "Tunisia",
            "Bulgaria",
            "Latvia",
            "Cuba",
            "Lebanon",
            "Cyprus",
            "Andorra",
            "Costa Rica",
            "Afghanistan",
            "Oman",
            "Uruguay",
            "Bangladesh",
            "Ivory Coast",
            "Burkina faso",
            "Albania",
            "Ghana",
            "Channel Islands",
            "Honduras",
            "Réunion",
            "Taiwan",
            "Jordan",
            "Malta",
            "San Marino",
            "Kyrgyzstan",
            "Mauritius",
            "Nigeria",
            "Senegal",
            "Bolivia",
            "Palestine",
            "Montenegro",
            "Vietnam",
            "Guinea",
            "Georgia",
            "Isle of Man",
            "DRC",
            "Sri Lanka",
            "Mayotte",
            "Kenya",
            "Djibouti",
            "Faeroe Islands",
            "Venezuela",
            "Martinique",
            "Guandeloupe",
            "Guatemala",
            "Brunei",
            "Paraguay",
            "Gibraltar",
            "Cambodia",
            "El Salvador",
            "Rwanda",
            "Trinidad and Tobago",
            "Madagascar",
            "Monaco",
            "Aruba",
            "Mali",
            "French Guiana",
            "Liechtenstein",
            "Togo",
            "Ethiopia",
            "Barbados",
            "Jamaica",
            "Congo",
            "Uganda",
            "French Polinesia",
            "Sint Maarten",
            "Liberia",
            "Bermuda",
            "Gabon",
            "Cayman Islands",
            "Macao",
            "Bahamas",
            "Guyana",
            "Zambia",
            "Guinea-Bissau",
            "Benin",
            "Eritrea",
            "Tanzania",
            "Saint Martin",
            "Myanmar",
            "Haiti",
            "Syria",
            "Libya",
            "Antigua and Barbuda",
            "Somalia",
            "Mozambique",
            "Angola",
            "Sudan",
            "Maldives",
            "Equatorial Guinea",
            "Laos",
            "New Calcedonia",
            "Dominica",
            "Fiji",
            "Mongolia",
            "Namibia",
            "Saint Lucia",
            "Curaçao",
            "Grenada",
            "Zimbabwe",
            "Belize",
            "Botswana",
            "Malwi",
            "Saint Kitts and Nevis",
            "St. Vincent Grenadies",
            "Eswatini",
            "Chad",
            "Greenland",
            "Seychelles",
            "Suriname",
            "MS Zaandam",
            "Gambia",
            "Nepal",
            "Montserrat",
            "Cabo Verde",
            "Turks and Caicos",
            "Vatican City",
            "Sierra Leone",
            "Mauritania",
            "St. Barth",
            "Bhutan",
            "Burundi",
            "Falkland Islands",
            "Sao Tome and Principe",
            "South Sudan",
            "Anguilla",
            "British Virgin Islands",
            "Caribbean Netherlands",
            "Papua New Guinea",
            "Timor-Leste",
            "Saint  Pierre Miquelon",
            "Yemen"});
            this.comboBox4.Location = new System.Drawing.Point(55, 356);
            this.comboBox4.Margin = new System.Windows.Forms.Padding(3, 2, 3, 2);
            this.comboBox4.Name = "comboBox4";
            this.comboBox4.Size = new System.Drawing.Size(220, 26);
            this.comboBox4.TabIndex = 9;
            // 
            // label1
            // 
            this.label1.AutoSize = true;
            this.label1.Location = new System.Drawing.Point(52, 88);
            this.label1.Name = "label1";
            this.label1.Size = new System.Drawing.Size(0, 17);
            this.label1.TabIndex = 10;
            // 
            // label2
            // 
            this.label2.AutoSize = true;
            this.label2.Location = new System.Drawing.Point(52, 184);
            this.label2.Name = "label2";
            this.label2.Size = new System.Drawing.Size(0, 17);
            this.label2.TabIndex = 11;
            // 
            // label3
            // 
            this.label3.AutoSize = true;
            this.label3.Location = new System.Drawing.Point(52, 284);
            this.label3.Name = "label3";
            this.label3.Size = new System.Drawing.Size(0, 17);
            this.label3.TabIndex = 12;
            // 
            // label4
            // 
            this.label4.AutoSize = true;
            this.label4.Location = new System.Drawing.Point(52, 384);
            this.label4.Name = "label4";
            this.label4.Size = new System.Drawing.Size(0, 17);
            this.label4.TabIndex = 13;
            // 
            // GraphsForm
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(8F, 16F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.ClientSize = new System.Drawing.Size(800, 450);
            this.Controls.Add(this.label4);
            this.Controls.Add(this.label3);
            this.Controls.Add(this.label2);
            this.Controls.Add(this.label1);
            this.Controls.Add(this.comboBox4);
            this.Controls.Add(this.comboBox3);
            this.Controls.Add(this.comboBox2);
            this.Controls.Add(this.comboBox1);
            this.Controls.Add(this.graphBttn);
            this.Controls.Add(this.graphImage);
            this.FormBorderStyle = System.Windows.Forms.FormBorderStyle.FixedSingle;
            this.Location = new System.Drawing.Point(230, 210);
            this.MaximizeBox = false;
            this.Name = "GraphsForm";
            this.ShowIcon = false;
            this.StartPosition = System.Windows.Forms.FormStartPosition.Manual;
            this.Text = "Covid-19 Graph";
            this.FormClosed += new System.Windows.Forms.FormClosedEventHandler(this.GraphsForm_FormClosed);
            ((System.ComponentModel.ISupportInitialize)(this.graphImage)).EndInit();
            this.ResumeLayout(false);
            this.PerformLayout();

        }

        #endregion

        private System.Windows.Forms.PictureBox graphImage;
        private System.Windows.Forms.Button graphBttn;
        private System.Windows.Forms.ComboBox comboBox1;
        private System.Windows.Forms.ComboBox comboBox2;
        private System.Windows.Forms.ComboBox comboBox3;
        private System.Windows.Forms.ComboBox comboBox4;
        private System.Windows.Forms.Label label1;
        private System.Windows.Forms.Label label2;
        private System.Windows.Forms.Label label3;
        private System.Windows.Forms.Label label4;
    }
}